colorScheme = "princess"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableCodeCopy = true


defaultBackgroundImage = "/img/background.jpg"
defaultFeaturedImage = "/img/background.jpg"

[header]
  layout = "fixed-fill-blur"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/background.jpg" # used in: hero, and card
  layoutBackgroundBlur = true
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false

[sitemap]
  excludedKinds = []

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showRelatedContent = false
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthor = true
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = [ "reddit", "email", "linkedin", "twitter", ]
  showZenMode = true